De-cal/6-Snack-FE

- src/app/(preview)/components-preview/page.tsx
- src/app/layout.tsx
- src/components/common/TextArea.tsx
- src/components/preview/DevNavBar.tsx
- src/constants/navigationLinks.ts
- src/types/textArea.types.ts
- 현재 개발 단계에서 각 기능 페이지로 빠르게 이동할 수 있는 방법이 없어, 개발 생산성이 저하되는 문제.
- 공통 컴포넌트의 테스트 및 미리보기를 위한 전용 페이지가 없었습니다.
- 반복적으로 사용되는 TextArea UI를 공통 컴포넌트로 추출하여 일관성 있게 사용할 필요가 있었습니다.
- components-preview 페이지 추가
→ /components-preview 경로로 접속 시 공통 컴포넌트들을 모아볼 수 있는 테스트용 페이지입니다.
- 페이지 하단 개발용 네비게이션 바 추가
→ 랜딩부터 예산 관리까지 총 17개 주요 경로를 빠르게 이동할 수 있도록 도와줍니다.
- TextArea 공통 컴포넌트 추가
→ 기본 스타일 및 placeholder 텍스트 포함
- P3 : 이런 방법도 있을 것 …
> chore: 개발용 nav바 추가,공통 컴포넌트 테스트용 페이지 추가, TextArea공통 컴포넌트 추가

- src/app/layout.tsx
- src/components/common/Desktop.tsx
- src/components/common/Mobile.tsx
- src/components/common/Tablet.tsx
- src/types/children.types.ts
- 기초 파일들 수정할게 있어서 수정하고, 간단한 로직 담겨있는 파일 업로드했습니다.
-
-
> chore: 기초적인 파일들 업로드 및 수정 [이태빈]

- src/app/(preview)/components-preview/page.tsx
- src/components/common/MemberList.tsx
- src/types/meberList.types.ts
- memberlist 공통 컴포넌트가 추가되었습니다. 
- 현재 Api와 연동을 고려하지않고 컴포넌트를 구현했습니다 참고 부탁드립니다.
- api와의 연동을 위한 코드 수정 및 리팩토링은 추후 공통 컴포넌트 작업이 끝나고 일괄적으로 처리 예정입니다.
> feat:memberlist 컴포넌트 추가[조성빈]

- src/app/(preview)/components-preview/page.tsx
- src/components/common/DropDown.tsx
- 드롭다운 컴포넌트 구현 및 추가 
- 현재 반응형 사이즈 미구현 (7.13 일까지 리팩토링 하면서 추가예정)
- 시안과 디자인 미세한 차이 약간 있음 
> feat:드롭다운 공통컴포넌트 구현[조성빈]

- src/components/common/ProductList.tsx
- src/providers/ModalProvider.tsx
- 모달 프로바이더 닫는 옵션을 추가했습니다.
- ProductList 공통 컴포넌트의 이미지 크기를 디자인 시안에 맞게 살짝 수정했습니다.
- 모달을 esc키를 누르거나, 백드롭을 클릭하는 것으로도 닫을 수 있게 하였습니다.
- ProductList의 사진이 디자인 시안과 비슷하도록 더 정교하게 크기를 맞추었습니다.
-
> refactor: 모달 프로바이더 닫기 옵션(esc, 백드롭 클릭) 추가, ProductList 이미지 수정 [이태빈]

- src/app/(main)/budgets/super-admin/_components/BudgetForm.tsx
- src/app/(main)/budgets/super-admin/page.tsx
- src/app/(main)/order-history/_components/PurchaseList.tsx
- src/app/(main)/order-history/_components/PurchaseSummary.tsx
- src/app/(main)/order-history/page.tsx
- src/constants/navigationLinks.ts
- `예산 폼/최고관리자 예산/구매 내역 확인` 컴포넌트와 페이지 피그마 UI를 기준으로 기본적인 형태를 구현했습니다.
- API연결, 버튼 동작, 데이터 fetch등 실제 로직은 구현되어 있지 않으며, 코드 내부 컨벤션이 팀 컨벤션과 일치하지 않을 수 있다는 점을 미리 알립니다. (MVP 구현 및 중간 발표 빠른 시연 테스트를 위해 기본UI골격으로 이루어진 미완성 코드를 PR요청합니다)
- `예산 폼/최고관리자 예산/구매 내역 확인` 컴포넌트와 페이지 피그마 UI를 기준으로 기본적인 형태를 구현했습니다.
- `/budgets/super-admin`, `/signup/super-admin`, `/order-history` 세 경로에서 페이지UI 확인 가능합니다.
- Comment 작성 시 Prefix로 P1, P2, P3 를 적어 주시면 …
> feat: `예산 폼/최고관리자 예산/구매 내역 확인` 컴포넌트&페이지 UI 구현; 리팩터링 개선 필수(MVP 우선); [김홍섭]

- src/components/common/DropDown.tsx
- 드롭다운 컴포넌트가 시안과 다르게 rounded가 적용되있던 현상 
- 드롭다운 컴포넌트가 시안과 다르게 rounded가 적용되있던 현상 수정
> fix:드롭다운 컴포넌트가 시안과 다르게 rounded가 적용되있던 현상 수정[조성빈]

- src/app/(preview)/components-preview/page.tsx
- src/components/layout/GeneralLayout.tsx
- 프리뷰 페이지에서 임포트 중복으로 되어있던거 제거 했습니다.
- GeneralLayout에 필요없는 주석을 삭제했습니다.
-
-
> fix: 오류 해결, import 중복 제거 [이태빈]

- src/app/(main)/products/[productId]/page.tsx
- 상품 상세 페이지 구현 
- 상품 상세페이지의 ui가 추가되었습니다. 
- subCategoryMenu, productDetail 두개의 공통 컴포넌트가 사용되었습니다.
- 반응형은 구현하지 않은 상태입니다.
- 공통 컴포넌트를 갖다 붙여놓은 상태로 실제 Api와 연동되지않은 상태입니다.
> feat:상품 상세페이지 ui 구현 및 추가 [조성빈]

- src/app/(preview)/components-preview/page.tsx
- src/components/common/RequestList.tsx
- 컴포넌트 사용하시는 분의 피드백 반영해서 수정했습니다.
- onClink props 추가
- 모바일일 때도 w-full로 늘어나도록 개선
- button을 공통 컴포넌트 Button 컴포넌트로 수정
-
> refactor: RequestList 피드백 반영 [이태빈]

- src/app/(main)/my/products/page.tsx
- src/components/common/ProductList.tsx
> feat: 상품 등록 내역 페이지 1차 UI 완성 [이태빈]

- src/components/common/SubCategoryItem.tsx
- subCategoryItem 컴포넌트에 '카테고리' 글자 추가
-
-
> refactor: subCategoryItem 컴포넌트 수정 [이태빈]

- src/components/preview/DevNavBar.tsx
- src/components/preview/types.ts
- src/constants/navigationLinks.ts
- 개발자 경험 향상을 위한 개발자 도구를 수정했습니다.
- 화면 우측 하단 등 특정 위치에 챗봇 박스 형태로 표시
- 대화 UI와 유사한 구조
- 항목별 정보 구분
---
| 상태        | 설명       |
|-------------|------------|
| 시작 전     | 회색    |
| 진행 중     | 파랑       |
| 리팩터링 중 | 주황       |
| 완성        | 초록       |
| QA 중       | 보라    |
> 💡 **상태는 직접 코드 변경으로만 반영됨** (DB 연동 아님)
---
1. **개발자 도구 플로팅 클릭** → 열기/닫기
2. `Ctrl + X` 또는 `Cmd + X` → 열기/닫기
3. `Esc` → 닫기
4. **바깥 영역 클릭** → 닫기
---
- 항목별 진행 상태 시각화 가능
---
- **역할 별 필터**
- **진행도 별 필터**
- **필터 초기화** (전체 해제)
> 💡 **필터는 토글 형식으로 동작** (켜기/끄기 가능)
---
- 각 페이지마다 맡은 역할 확인 가능
> chore: 개발자 도구 수정 [이태빈]

- src/app/(main)/cart/order-confirmed/page.tsx
- src/app/(main)/cart/page.tsx
- src/app/(main)/products/page.tsx
- src/components/preview/DevNavBar.tsx
- 빈 페이지에 스니펫 적용
- Devtools에 카테고리 정렬 추가
-
-
> refactor: 빈 페이지 rfc 스니펙 적용, Devtools 카테고리 정렬 추가 [이태빈]

- package-lock.json
- package.json
- src/app/(main)/my/products/page.tsx
- src/app/(preview)/components-preview/PreviewMockData.ts
- src/app/(preview)/components-preview/page.tsx
- src/components/common/ProductList.tsx
- src/components/preview/DevNavBar.tsx
- ProductList 공통 컴포넌트 Props를 받아서 데이터를 처리할 수 있게끔 리팩터링 하였습니다.
- 
-
> refactor: ProductList 공통 컴포넌트 2차 기능 리팩터링 [이태빈]

- package-lock.json
- package.json
- src/app/(main)/my/products/page.tsx
- src/app/(main)/order-manage/_components/Order.tsx
- src/app/(preview)/components-preview/PreviewMockData.ts
- src/app/(preview)/components-preview/page.tsx
- src/components/common/ProductList.tsx
- src/components/common/RequestList.tsx
- src/components/preview/DevNavBar.tsx
- src/constants/navigationLinks.ts
- src/lib/api/fetchClient.api.ts
- src/lib/utils/.gitkeep
- src/lib/utils/DateFormat.util.ts
- RequestList 공통 컴포넌트 2차 기능 리팩터링 했습니다. props와 onClick함수로 데이터를 전달 받을 수 있습니다.
- 우주님이 만드신 OrderManage 페이지에서 제가 만든 컴포넌트 사용중이셔서 배포 오류가 나서 그 부분만 오류 수정했습니다.
-
-
> refactor: RequestList 공통 컴포넌트 2차 기능 리팩터링 [이태빈]

- src/app/(main)/my/products/page.tsx
- src/app/(main)/order-manage/_components/Order.tsx
- src/app/(preview)/components-preview/MockData.ts
- src/app/(preview)/components-preview/page.tsx
- src/components/common/OrderManageModal.tsx
- OrderManageModal에서 props를 받을 수 있도록 기능적 리팩터링 진행했습니다.
- onClick으로 함수를 받을 수 있습니다.
- type으로 반려 / 승인을 정할 수 있습니다.
- order에 data를 담아서 props로 보내면 자동으로 렌더링 되도록 만들었습니다.
-
-
> feat: OrderManageModal 2차 기능 리팩터링 [이태빈]

- .env.example
- src/app/(auth)/login/page.tsx
- 로그인 백엔드 연동했습니다.
- 일단은 급하게 쿠키랑 로그인이 필요하신 분들을 위해서 로그인 기능만 간단하게 연동해둔 상황입니다.
-
-
> feat: 로그인 백엔드 연동(로그인 기능만 일단 간단하게 구현) [이태빈]

- src/app/(auth)/signup/[inviteId]/page.tsx
> 어떤 기능을 구현한건지, 이슈 대응이라면 어떤 이슈인지 PR이 열리게 된 계기와 목적을 Reviewer 들이 쉽게 이해할 수 있도록 적어 주세요  
- 일반유저, 관리자 회원가입 페이지 UI & 백엔드 API 연동을 완료하였습니다.
- 유저가 /signup/:inviteId 링크를 통해 회원가입 페이지에 들어가면, 해당 유저의 이름과 email 값이 prepopulated 되어 나옵니다.
- 유저가 비밀번호를 입력하고 가입하기 버튼을 눌렀을때, db에 유저 정보가 생성되고 기존의 inviteId에 해당하는 데이터의 isUsed field 값이 true로 되는 것을 확인하였습니다. 아래 예시 참고해주세요.
- <img width="1224" height="74" alt="Screenshot 2025-07-22 at 9 17 11 PM" src="https://github.com/user-attachments/assets/1d0b94b2-a1c1-47ee-92d6-55f87f310327" />
- 스크린샷:
---
- 없음
---
- 디바이스 사이즈가 **tablet**일 때, 최상위 div에서 `padding-top` 값이 적용되지 않는 이슈가 있습니다.  
- 그 외에는 최대한 디자인 시안과 유사하게 구현하였습니다.
- 문제의 코드:
```tsx
<div …
```
> feat: 일반 유저, 관리자 회원가입 페이지 UI 반응형 & API 연동 [이지수B]

- src/app/(main)/my/order-list/[orderId]/page.tsx
- 주문 상세 페이지에 장바구니 다시 담기 기능 구현
- 주문 상세 페이지에 장바구니 다시 담기 기능 구현
- 다시 담기 성공or실패 시 알림창
- 처리 완료시 장바구니 페이지로
- 카트 API 연동이 아직 안된 것 같아 우선 페이지에 타입,API 정의해놓음
> feat: 주문 상세 페이지에 장바구니 다시 담기 기능 구현 [장원빈]

- src/app/(main)/cart/_components/CartItem.tsx
- src/app/(main)/cart/_components/CartItemQuantityDropdown.tsx
- src/app/(main)/cart/page.tsx
- src/app/(main)/my/products/page.tsx
- src/app/(preview)/components-preview/navigationLinks.ts
- src/lib/api/cart.api.ts
- src/lib/api/product.api.ts
- src/types/cart.types.ts
- src/types/product.types.ts
- 장바구니 페이지 2차 기능 구현 완료 했습니다.
1. 장바구니 조회 - O
2. 장바구니 상품 선택 / 해제 - O
2-1. 장바구니 상품 전체 선택 / 해제 - △
3. 장바구니 상품 삭제 - O
4. 상품 수량 선택 - △
5. 바로 요청(페이지만 이동 시키기) - O
상품 전체 선택 / 해제, 상품 수량 선택은 API 미개발 상태로 임시로만 작성해뒀습니다. API 작성되는 대로 연동 시킬 예정입니다.
-
- P2 : 반영을 적극적으로 고려해 주시면 좋을 것 같아요 …
> feat: 장바구니 페이지 2차 기능 구현 완료 [이태빈]

- src/app/(main)/my/products/page.tsx
- src/app/(main)/products/_components/ProductsPageContent.tsx
- src/components/common/QuantityDropdown.tsx
- src/components/common/Toast.tsx
- src/hooks/useDeviceType.ts
- 디바이스 타입 판별 커스텀 훅으로 분리, 토스트 모달 수정, 수량 드롭다운 수정
- react-responsive를 사용해서 디바이스 타입을 판별하는 함수를 커스텀 훅으로 분리했습니다.
- 토스트 모달 세부적인 리팩터링 진행했습니다.
- 수량 드롭다운 리팩터링 진행
-
> refactor: 디바이스 타입 판별 커스텀 훅으로 분리, 토스트 모달 수정, 수량 드롭다운 수정 [이태빈]

- src/app/(main)/cart/_components/CartItem.tsx
- src/app/(main)/cart/order/_components/OrderPageContent.tsx
- src/app/(main)/cart/page.tsx
- src/components/common/Toast.tsx
- 장바구니 상품 선택 토스트 추가, 유저 입장 장바구니 페이지 리팩터링
1. 토스트 애니메이션, 텍스트, 타이머 클린업, 위치(픽스트? 앱솔?), 안의 내용 수정 - ✅
2. 1개 이상 수량 선택하지 않았을 때 토스트 모달로 변경 - ✅
3. 구매 요청 중에 버튼 비활성화(일반 유저, 관리자 페이지 모두) - ✅
4. 토스트 모달을 그냥 opacity로만 해두니까 레이어 가려지는 문제 (z-index도 조건부 주면 해결될 듯) - ✅
-
- P2 : 반영을 적극적으로 고려해 주시면 …
> refactor: 장바구니 페이지(유저, 관리자 입장) 3차 기능 구현 완료 [이태빈]

- src/app/(main)/order-manage/[orderId]/page.tsx
- src/hooks/useOrderDetail.ts
- src/lib/api/orderDetail.api.ts
- src/types/order.types.ts
- 관리자, 최고관리자가 유저로부터 온 구매요청을 관리할수 있는 페이지 구현하였습니다.
- react query 사용하여 만들었습니다.
- 승인/반려 api 추가 연동 예정입니다.
-
-
> feat: 관리자 주문요청 관리 페이지 구현 [이지수B]

- src/app/(auth)/signup/super-admin/page.tsx
- src/app/(main)/manage/budgets/_components/BudgetFormUI.tsx
- src/app/(main)/order-history/[orderId]/page.tsx
- src/app/(main)/order-history/page.tsx
- src/hooks/useOrderHistory.ts
- npm run build시 발생하는 린트 오류 해결이 목적
1. page.tsx ✅ useEffect import 제거 (사용되지 않음)
✅ setFormError 변수 제거 (사용되지 않음)
2. BudgetFormUI.tsx ✅ let num → const num으로 변경 (prefer-const 규칙)
3. page.tsx ✅ TArrowDirection 타입 삭제 (사용되지 않음)
✅ 빈 객체 타입 {} → Record<string, never>로 변경
✅ router 변수 삭제 (사용되지 않음)
✅ index 매개변수 삭제 (사용되지 않음)
✅ <img> → <Image> 컴포넌트 변경 및 Next.js Image import 추가 ✅ CSS 클래스 중복 제거 (sm:outline 중복 제거)
4. page.tsx ✅ clsx import 제거 (사용되지 않음)
✅ fileIcon import 제거 (사용되지 않음)
✅ 사용되지 않는 변수들 제거: budgetLoading, budgetError, purchaseListLoading, purchaseListError, sortBy, dropdownOpen, setDropdownOpen
5. useOrderHistory.ts ✅ any 타입을 구체적인 …
> refactor: 맡은 컴포넌트와 함수에 대해 린팅 오류 개선사항 적용 [김홍섭]

- next.config.ts
- src/app/(auth)/signup/[inviteId]/page.tsx
- src/app/(main)/order-manage/[orderId]/page.tsx
- src/app/(main)/products/_components/ProductsPageContent.tsx
- src/components/common/ProductRegistrationForm.tsx
- src/lib/api/fetchClient.api.ts
- npm run build시 나는 린트 에러 제가 맡은 부분 다 해결했습니다.
-
-
> fix: npm run build 에러 해결 [이지수B]

- next.config.ts
- src/app/(preview)/components-preview/DevTools.tsx
- src/components/common/QuantityDropdown.tsx
- src/lib/api/order.api.ts
> fix: 엄격 모드에서 발생하는 build 오류 해결 [이태빈]

- next.config.ts
> next config 수정 [이태빈]

- next.config.ts
- src/app/(main)/my/order-list/page.tsx
- src/components/common/MyRequestList.tsx
- src/components/common/ProductDetail.tsx
- src/components/ui/Badge.tsx
- src/lib/api/myOrderList.api.ts
- src/lib/utils/converStatus.util.ts
- src/types/myOrderList.types.ts
- 나의 구매요청 내역 페이지 구현 
- 나의 구매요청 내역 페이지를 구현하였습니다. 
> feat:나의 구매요청 내역 페이지 구현 [조성빈]

- src/app/(main)/cart/order-confirmed/[orderId]/page.tsx
- src/app/(main)/cart/order/_components/OrderPageContent.tsx
- src/app/(main)/cart/page.tsx
- src/lib/api/order.api.ts
- src/types/order.types.ts
- 주문 확인 페이지로 이동 시 URL에 동적 파라미터로 orderId 넘겨주도록 수정했습니다.
-
-
> refactor: 주문 확인 페이지로 이동 시 URL에 동적 파라미터로 orderId 넘겨줌 [이태빈]

- src/app/(main)/products/[productId]/page.tsx
- src/components/common/MenuDropdown.tsx
- src/components/common/MobileCategoryMenu.tsx
- src/components/common/ProductDetail.tsx
- src/components/common/ProductDetail/CartAndLikeButtons.tsx
- src/components/common/ProductDetail/ProductActions.tsx
- src/components/common/SubCategoryItem.tsx
- src/components/layout/AuthenticatedHeader.tsx
- src/hooks/useCurrentSubCategory.ts
- 상품상세페이지에 subCategoryItem 공통컴포넌트 추가 
- 사용하지 않는 기능 제거 
- 상품상세페이지에 subCategoryItem 공통컴포넌트 추가 
- 좋아요 버튼 및 상품수정 기능 주석처리 
> fix:상품상세페이지에 subCategoryItem적용, 좋아요버튼 및 상품수정기능 주석처리[조성빈]

- src/app/(main)/order-history/page.tsx
- src/hooks/useAdminOrders.ts
- src/hooks/useOrderHistory.ts
- 리액트쿼리 캐싱기능을 활용(재패칭 X)이 목적입니다.
- prev, next에 마우스모양이 손가락모양으로 변경해야 합니다.
- 호버박스 위치 조정해야 함.
- 리액트쿼리 캐싱기능을 활용함.
- prev, next에 마우스모양이 손가락모양으로 변경함
- 호버박스 위치 조정함.
- order-history 페이지에서 확인 가능합니다.
- P3 : 이런 방법도 있을 것 같아요~ 등의 사소한 의견입니다 …
> refactor: 최고관리자 구매내역확인 페이지에서 피드백 수정사항 반영

- src/app/(preview)/components-preview/navigationLinks.ts
> chore: 진행도 업데이트 [이태빈]

- src/app/(auth)/login/page.tsx
- 로그인 버튼 비활성화 QA 반영했습니다
- #156 
-
-
> refactor: 로그인 버튼 비활성화 QA 반영 [이태빈]

- src/app/(main)/manage/budgets/_components/BudgetFormUI.tsx
- src/app/(main)/manage/budgets/page.tsx
- src/lib/api/budgets.api.ts
- 예산 입력란 3자리마다 쉼표 표시 및 1억 미만 숫자 자유 입력 지원 필요
- 0원/빈값/플레이스홀더 처리 명확화 필요
- 수정하기 버튼에 cursor-pointer 적용 필요
- alert → Toast 공통 컴포넌트로 알림 방식 일원화 필요
- 예산 입력란 3자리마다 쉼표 표시 및 1억 미만 숫자 자유 입력 지원
- input pattern 속성 제거로 브라우저 기본 validation 비활성화
- 0원/빈값/플레이스홀더 처리 명확화
- 수정하기 버튼에 cursor-pointer 적용
- alert → Toast 공통 컴포넌트로 알림 방식 일원화
- BudgetResponse 타입 명시 및 useQuery 제네릭 적용
- API 반환 타입 명확화 및 TypeScript 에러 제거
- /manage/budgets 페이지에서 확인해볼 수 있습니다.
- Review는 특수한 케이스가 아니면 Reviewer로 지정된 시점 기준으로 3일 이내에 진행해 …
> refactor: 예산 관리 UI/UX 및 타입 안정성 개선 [김홍섭]

- src/app/(main)/cart/_components/CartItem.tsx
- src/app/(main)/cart/order/_components/OrderItem.tsx
- src/components/common/OrderManageModal.tsx
- src/components/common/RequestList.tsx
> fix: 빌드 에러 수정 [이태빈]

- next.config.ts
- src/components/common/Input.tsx
- src/hooks/useAdminOrders.ts
- src/hooks/useOrderHistory.ts
- src/lib/api/auth.api.ts
- src/lib/api/fetchClient.api.ts
- 맡은 6개의 파일들에 대해 빌드시 esLint 문법 오류를 개선했습니다. (npm run build로 재 빌드시 항목이 없어진 것 확인)
- 맡은 6개의 파일들에 대해 빌드시 esLint 문법 오류를 개선하기 위한 코드 변경이 적용되었습니다.
- npm run build 시 이 PR에서 수정된 해당 항목들이 나타나지 않으면 됩니다.
- P3 : 이런 방법도 있을 것 같아요~ 등의 사소한 의견입니다 …
> build: 맡은 파일들에 대한 esLint 빌드 문법오류 수정 [김홍섭]

- src/app/(main)/manage/users/_components/User.tsx
- src/app/(main)/order-manage/_components/Order.tsx
- src/app/(main)/profile/_components/ProfileComponent.tsx
> QA: 우주님 프론트엔트 코드리뷰 주석 추가 [이태빈]

- src/app/(preview)/components-preview/page.tsx
- src/components/common/DogSpinner.tsx
- src/components/common/DropDown.tsx
- src/components/common/MyRequestList.tsx
- src/components/common/ProductDetail.tsx
- src/components/common/ProductDetail/CartAndLikeButtons.tsx
- src/components/common/ProductDetail/ProductBasicInfo.tsx
- src/components/common/ProductDetail/ProductImage.tsx
- src/components/common/Toast.tsx
- src/components/common/spinnerAnimate.tsx
- src/lib/api/addToCart.api.ts
- src/types/meberList.types.ts
- src/types/productDetail.types.ts
- src/types/toast.types.ts
- 태빈님께서 주석으로 남겨주신 QA를 반영하였습니다.
- 태빈님께서 주석으로 남겨주신 QA를 반영하였습니다.
> fix: 태빈님이 남겨주신 QA를 반영하였습니다 [조성빈]

- src/components/common/ConfirmationModal.tsx
- 컴포넌트 선언을 `export default function으로 변경` 적용하는것이 목표입니다.
- `export default function으로 변경` 적용했습니다.
- 없습니다.
> fix: @rakaso598 수정사항 - `export default function으로 변경` 적용

- src/app/(main)/cart/order-confirmed/[orderId]/page.tsx
- src/app/(main)/my/order-list/[orderId]/page.tsx
- src/app/(main)/order-history/[orderId]/page.tsx
- src/lib/api/orderHistory.api.ts
- 스키마 변경으로 인한 응답 변경
- 구매 완료 페이지 관리자/일반유저 디자인이 다름
- 피그마와 세세한 디자인이 다름
- 변경된 응답에 맞게 타입 및 api 수정
- 구매 완료 페이지 일반유저 일때와 관리자일 때 다르게 표시
- 피그마에 맞게 디자인 수정
-
> refacotr: 내 구매 요청 내역 및 구매 완료료 디자인 개선 및 새 응답에 맞게 수정 [장원빈]

- src/app/(main)/cart/order-confirmed/[orderId]/page.tsx
- 구매 완료 페이지 관리자 이상이 구매를 하게 되면 구매 완료 메시지 변경
- 구매 완료 메시지 관리자급은 ‘구매 요청이 완료되었습니다’가 아니라 ‘구매가 완료되었습니다.’로 변경
-
> refactor:주문 완료 메시지 관리자/일반유저 구분 [장원빈]

- src/components/common/InviteMemberModal.tsx
> fix:state 타입 정의 [김우주]

- next.config.ts
- src/app/(main)/cart/order/_components/OrderPageContent.tsx
- src/app/(main)/cart/page.tsx
- 장바구니 페이지에서 관리자 이상일 때 버튼 텍스트 `구매 요청하기` -> `구매하기`로 수정
- 장바구니 주문 페이지 비활성화 중 텍스트 크기 조절
-
-
> refactor: 장바구니 페이지에서 관리자 이상일 때 버튼 텍스트 수정, 장바구니 주문 페이지 비활성화 중 텍스트 수정 [이태빈]

- next.config.ts
- src/app/(auth)/signup/super-admin/page.tsx
- src/app/(main)/manage/budgets/_components/BudgetFormUI.tsx
- src/app/(main)/manage/users/_components/User.tsx
- src/app/(main)/my/order-list/page.tsx
- src/app/(main)/profile/_components/ProfileForm.tsx
- src/app/(preview)/components-preview/page.tsx
- src/components/common/InviteMemberModal.tsx
- src/hooks/useProductDetail.ts
- src/lib/api/budgets.api.ts
- src/lib/api/productDetail.api.ts
- src/lib/api/user.api.ts
- src/types/auth.types.ts
> fix:linting 오류 다잡기 [김우주]

- src/app/(main)/order-history/page.tsx
- 모달창의 위치가 피그마와 다름(너무 떨어져있음)
- 금액이 높아져서 그런지 두 줄로 나타나는데 한줄로 나타나고 가로로 늘어나는 건 어떨까요?
- 상품 정보 링크 밑줄 제거하는 걸로 알고 있습니다.
- 요청인과 같이 상품 정보 또한 일정 길이를 넘어가면 ...으로 표현되게 하면 어떨까요?
- 주문금액이 실제 주문 금액과 다름(배송비 포함되지 않음)
- 각 개선사항별로 커밋 나누어 푸쉬했습니다
- 관리자 구매내역상세페이지에서 확인 가능합니다
- P2 : 반영을 적극적으로 고려해 주시면 …
> QA: 구매 내역 확인 개선사항 적용 [김홍섭]

- src/app/(main)/my/order-list/page.tsx
- src/components/common/MyRequestList.tsx
- feat: 내 구매 요청 내역 페이지에서 상품명을 클릭시 내 구매 요청 내역 상세 페이지로 이동하는 기능 추가
- feat: 내 구매 요청 내역 페이지에서 상품명을 클릭시 내 구매 요청 내역 상세 페이지로 이동하는 기능 추가
> feat: 내 구매 요청 내역 페이지에서 상품명을 클릭시 내 구매 요청 내역 상세 페이지로 이동하는 기능 추가[조성빈]

- src/components/common/MenuDropdown.tsx
- src/components/common/ProductDetail.tsx
- src/components/common/ProductDetail/ProductActions.tsx
- src/components/common/ProductDetail/ProductImage.tsx
- src/components/common/QuantityDropdown.tsx
- src/components/layout/AuthenticatedHeader.tsx
- src/components/layout/GuestHeader.tsx
- src/components/ui/Badge.tsx
- QA 사항을 반영하여 리팩터링하였습니다. 
- 드롭다운 메뉴의 부자연스러움 해결 
- 3점 메뉴 해결
- 상품 기본정보 +버튼을 눌렀을때 상품 이미지가 같이 이동하는 현상 해결 
> fix: 모든 QA사항 반영하여 리팩터링 [조성빈]

- src/lib/api/fetchClient.api.ts
> chore: fetchClient BASE_URL 수정 [이태빈]

- src/app/error/page.tsx
- src/lib/api/fetchClient.api.ts
> fix: cookieFetch 오류수정 [이지수B]

- src/app/(main)/profile/_components/ProfileForm.tsx
- 프로필 슈퍼 어드민이 아닐때 기업명이 안나오는 버그 수정 
-프로필 슈퍼 어드민이 아닐때 기업명이 안나오는 버그 (프롭스로 안내려줌)
-
> fix: 프로필 슈퍼 어드민이 아닐때 기업명이 안나오는 버그 수정 [김우주]

- src/app/(main)/cart/order/_components/OrderPageContent.tsx
- src/app/(main)/cart/page.tsx
- src/components/common/RequestList.tsx
- src/components/svg/CheckIconSvg.tsx
- src/components/svg/ExclamationMarkIconSvg.tsx
- src/lib/api/orderManage.api.ts
- src/stores/orderStore.ts
- src/types/order.types.ts
- Zustand로 order 정보 관리, orderId 타입 변경, svg 컴포넌트 수정
1. Zustand 라이브러리를 사용하여서 order 정보를 전역 관리 함으로써 결제 모듈 페이지 이동 시에 order 정보 활용
2. 스키마 수정에 따른 orderId 타입 변경
3. svg 컴포넌트 props 등 약간의 수정
-
> feat: Zustand로 order 정보 관리, orderId 타입 변경, svg 컴포넌트 수정 [이태빈]

- src/app/(toss-payments)/checkout/page.tsx
- src/app/(toss-payments)/fail/page.tsx
- src/app/(toss-payments)/success/page.tsx
- 토스페이먼츠 결제 모듈 페이지 구현
1. 결제 모듈 연동(zustand로 전역 상태 관리 및 보안을 위한 일회성 상태 관리 : 새로고침 하거나 다른 페이지로 이동 시 다시 돌아오게 되면 유효하지 않은 상태로 변경) - ✅ 
---
2. 결제 모듈 그려지는 동안 로딩 스피너 적용 - ✅
---
3. zustand에 order정보가 없을 때 '유효하지 않은 주문 정보'라는 UI 생성 - ✅
---
4. 결제 승인 API 페이지에서, Zustand로 관리하는 order의 totalPrice와 쿼리 파라미터의 amount 값이랑 동일한지 비교 후 올바르지 않으면, 결제 실패로 이동 - ✅
---
5. 결제 조회 및 결제 취소를 위해서 결제 승인 외부 API를 호출할 때 paymentKey, orderId를 DB에 저장 - ✅
---
6. 구매 성공 or 실패했을 때 UI 구현 - ✅
---
7. 닫기 버튼 클릭 시 **성공** -> 주문 완료 페이지 / **실패** -> 장바구니로 이동 - ✅
- 
- Reviewer 분들은 좋은 코드를 …
> feat: 토스페이먼츠 결제 모듈 페이지 구현 [이태빈]

- src/app/(auth)/signup/super-admin/page.tsx
- npm run build 시 오류
- 사용하지 않는 줄을 제거하여 해결
- npm run build 시 오류 해결
> fix: 빌드 오류 수정 [김홍섭]

- src/app/(auth)/signup/[inviteId]/page.tsx
- src/app/(main)/order-manage/[orderId]/page.tsx
- src/app/(main)/products/_components/ProductsPageContent.tsx
- 상품페이지, 관리자 구매요청내역 상세, 회원가입 페이지 웹 접근성 개선하였습니다.
-
-
> feat:웹 접근성 개선

- .gitignore
- next.config.ts
- package-lock.json
- package.json
- sentry.edge.config.ts
- sentry.server.config.ts
- src/app/(auth)/login/_components/FormErrorMessage.tsx
- src/app/(auth)/login/page.tsx
- src/app/(main)/cart/order/_components/OrderPageContent.tsx
- src/app/(main)/cart/page.tsx
- src/app/(main)/my/favorites/page.tsx
- src/app/(main)/my/products/page.tsx
- src/app/(toss-payments)/checkout/page.tsx
- src/app/(toss-payments)/fail/page.tsx
- src/app/(toss-payments)/success/page.tsx
- src/app/error/page.tsx
- src/app/global-error.tsx
- src/components/common/TextArea.tsx
- src/components/common/Toast.tsx
- src/components/ui/Button.tsx
- src/instrumentation-client.ts
- src/instrumentation.ts
> refactor: 웹 접근성 고려 코드 리팩터링, 센트리 적용 [이태빈]

- src/middleware.ts
- 사용자 역할(일반유저, 관리자, 최고관리자)에 따라 접근하면 안 되는 페이지에 접근하는 것을 방지하고, 잘못된 접근 시 에러 페이지로 안내하는 문제를 해결합니다.
- JWT 토큰에서 역할 정보를 추출하여,
- 일반유저는 6개 주요 관리/구매 경로 접근 차단
- 관리자/최고관리자는 장바구니-주문 접근 차단
- 관리자는 예산관리, 회원관리 접근 차단
- 위 조건에 해당하면 /error로 리디렉션 처리
- 각 역할별 계정으로 로그인 후,
일반유저가 /manage/users, /order-manage 등 접근 시 /error로 이동되는지 확인
- 관리자가 /cart, /manage/budgets 등 접근 시 /error로 이동되는지 확인
- 최고관리자가 /cart 접근 시 /error로 이동되는지 확인
- 정상적으로 접근 가능한 경로는 그대로 접근되는지 확인
- Review는 특수한 케이스가 아니면 Reviewer로 지정된 시점 기준으로 3일 이내에 …
> feat: 역할별 접근제어 및 에러페이지 리디렉션 추가

- src/app/(main)/products/_components/SubCategoryTabs.tsx
- src/components/common/DropDown.tsx
- src/components/common/ProductDetail/CategoryNavigation.tsx
- src/components/common/ProductGrid.tsx
- src/components/common/ProductRegistrationForm.tsx
- src/components/layout/AuthenticatedHeader.tsx
- src/hooks/useProductRegistrationForm.ts
- src/lib/schemas/product.schema.ts
> 어떤 기능을 구현한건지, 이슈 대응이라면 어떤 이슈인지 PR이 열리게 된 계기와 목적을 Reviewer 들이 쉽게 이해할 수 있도록 적어 주세요  
- QA 관련하여 개선사항 적용했습니다
1. 하위카테고리 선택하는 곳에 `cursor-pointer` 적용 → **완료**
2. "스낵 > 과자" 부분 `py-[14px]` 적용 여부  
→ 디자인 시안에서 `pt-14px`, `pb-10px`로 나와 있어 우선 변경하지 않았습니다.  
3. 상품 이름, 가격 텍스트 스타일 변경  
→ 모바일/태블릿에서 `text-[16px]/[20px] text-primary-400` 적용.  
→ 데스크탑은 기존 `text-lg/[22px]` 유지.  
→ 텍스트 컬러는 디자인 시안에서 `black-400`이었지만 내부 black 색상은 명시된 hex가 없어 디폴트 black 사용.
4. 구매 횟수 `text-[13px]/[16px] text-secondary-500` 적용 → **완료**
5. 상품 등록 텍스트 밀림 현상 → **모달 height 조정으로 해결**
6. 텍스트 스타일 재확인 필요 → **피그마 시안 기준으로 확인 완료**
---
1. 취소/등록하기 버튼 고정 너비 → **모바일에서는 `w-full` 적용으로 해결**
2. Dropdown `h-[56px]`로 변경  
→ `height`를 prop으로 받을 수 있도록 설정하고, …
> refactor: 상품 목록 페이지 & 상품 등록 모달 QA 반영 [이지수B]

- src/app/(auth)/signup/super-admin/page.tsx
- src/components/common/Input.tsx
- 최고관리자 회원가입 시 버튼이 활성화 안되는 문제
- name필드가 폼에 포함되어 있지 않았던 문제로 인해 isValid가 항상 false가 되었음.
- name 입력 필드를 폼에 추가
- 최고관리자 회원가입 버튼 활성화 및 가입
> fix: 최고관리자 회원가입 폼 입력시 버튼 활성화 오류 해결

- src/components/common/RequestList.tsx
- 테이블로 만들어 봤는데 많이 깨져서 다시 div로 바꿨습니다
-
-
> fix: 시멘틱 태그 수정 [김우주]

- src/components/svg/XIconSvg.tsx
- XIconSvg에 cursor-pointer 제거하고 그냥 className 프롭스로 부모에서 내려주어서 커스터마이징 하게 변경하였습니다.
-
-
> refactor: XIconSvg 기본 cursor-pointer 설정 제거 [이지수B]

- src/app/(main)/manage/users/_components/User.tsx
- src/app/(main)/order-manage/_components/Order.tsx
- src/app/(main)/profile/_components/ProfilePasswordSection.tsx
- src/components/common/OrderManageModal.tsx
- src/components/common/RequestList.tsx
- src/hooks/usePendingOrders.ts
- src/lib/api/orderManage.api.ts
- order ui 수정 및 페이지 네이션 수정 
-
-
> fix: order ui 수정, 페이지네이션 수정/ 프로필 비밀번호 ui 수정 [김우주]

- src/app/(main)/cart/_components/CartItem.tsx
- src/app/(main)/cart/page.tsx
- 즉시 구매 시 구매 내역 확인에 stale 타임으로 인한 fetch가 안되어서 invalidQueries 적용했습니다.
-
-
> refactor: 즉시 구매 시 구매 내역 확인 invalidQueries 적용 [이태빈]

- src/app/(main)/order-history/page.tsx
- src/hooks/useBudgets.ts
- 관리자 구매내역확인 "즉시 요청" 뱃지가 어색
- useBudgets 쿼리 키 "companyId" 추가
- 관리자 구매내역확인 "즉시 요청"->"즉시 구매" 로 문구 개선
- useBudgets 쿼리 키 "companyId" 추가로 리액트쿼리 동작 개선
- 구매내역확인페이지에서 즉시 구매 시 뱃지가 제대로 "즉시 구매"로 표현됩니다
-  useBudgets 쿼리 키 "companyId" 추가로 리액트쿼리의 쿼리 키를 구체화 함에 따라 예측가능한 동작을 예상
- P2 : 반영을 …
> refactor: 관리자 구매내역확인 "즉시 요청"->"즉시 구매"로 변경, useBudgets 쿼리 키 "companyId" 추가 및 staleTime 제거 [김홍섭]

- src/app/(auth)/signup/super-admin/page.tsx
- src/app/(main)/manage/budgets/page.tsx
- src/app/(main)/order-history/page.tsx
- 맡은 주요 페이지에 로딩 스피너 적용
- 로딩 스피너를 임포트 및 적용했습니다
- 로딩 시 스피너가 보입니다
> feat: 맡은 각 주요 페이지에 로딩 스피너 적용 [김홍섭]

- src/app/(main)/manage/users/_components/User.tsx
- src/app/(main)/order-manage/_components/Order.tsx
- src/app/(main)/profile/_components/ProfileForm.tsx
- src/components/ui/SearchBar.tsx
- src/lib/api/orderManage.api.ts
> fix: 프로필 기업명 수정될 수 있게 변경 [김우주]

- src/app/(main)/my/order-list/page.tsx
- src/components/common/ProductDetail/CartAndLikeButtons.tsx
- 찜하기 버튼 border영역 까지 클릭 가능하게 수정 
- 내 구매요청 내역 주문 금액에 배송비 포함
> hotfix: 찜하기 버튼 border영역 까지 클릭 가능하게 수정 및 내 구매요청 내역 주문 금액에 배송비 포함 [조성빈]

- src/app/(main)/cart/page.tsx
- src/app/(toss-payments)/checkout/page.tsx
- src/app/(toss-payments)/success/_components/SuccessPageContent.tsx
- src/app/(toss-payments)/success/page.tsx
- src/components/common/DogSpinner.tsx
- src/providers/AuthProvider.tsx
- 여러 자잘한 에러, 오타 수정, 불필요한 코드 삭제했습니다.
- params 오타 수정
- 불필요한 tailwind 삭제
- env 키 NEXT_PUBLIC으로 변경 등
-
> fix: 여러 자잘한 에러, 오타 수정, 불필요한 코드 삭제 [이태빈]

- src/app/(main)/cart/_components/CartItem.tsx
- src/app/(main)/order-manage/_components/Order.tsx
- src/app/(toss-payments)/checkout/page.tsx
- src/app/(toss-payments)/success/_components/SuccessPageContent.tsx
- src/components/common/OrderManageModal.tsx
- src/hooks/useDeleteProduct.ts
- src/lib/api/orderManage.api.ts
- src/types/cart.types.ts
- src/types/order.types.ts
- 유저 구매요청 승인부분 토스 결제 모듈 연동 및 자잘한 수정
- 유저가 구매요청한 내용을 관리자가 승인할 때도 이제 토스 결제모듈로 연동 되도록 수정 완료했습니다.
- 그 외에 자잘한 수정 했습니다.
-
> refactor: 유저 구매요청 승인부분 토스 결제 모듈 연동 및 자잘한 수정 [이태빈]

- src/app/(main)/cart/order/_components/OrderPageContent.tsx
> fix: 버셀 빌드 오류 해결 [이태빈]

- src/app/(main)/order-history/page.tsx
- 호버박스에 파란테두리가 있어 제거해야 함
- border-2 border-blue-400 속성 제거
- 오더히스토리페이지에서 더이상 파란 테두리가 뜨지 않아야 함
> fix: 호버박스 파란테두리 제거

- src/components/common/ProductGrid.tsx
- src/types/product.types.ts
> fix: 타입 에러 해결... [이태빈]

- src/app/(main)/profile/_components/ProfileForm.tsx
- src/components/common/InviteMemberModal.tsx
- src/components/common/Toast.tsx
- src/lib/schemas/email.schema.ts
- 이메일 유효성 검사 및 토스트 z인덱스 수정
-
-
> fix: 이메일 유효성 검사 및 토스트 z인덱스 수정 [김우주]

- src/app/(auth)/login/page.tsx
- src/app/(main)/my/favorites/page.tsx
- src/providers/AuthProvider.tsx
- 찜 목록, 로그인, 로그아웃 수정 했습니다.
- 찜 목록 페이지 하트 이미지 수정
- 로그인 버튼 비활성화 -> 활성화
- 로그인 요청 실패 시 메시지 세분화
- 로그아웃 시 랜딩 페이지로 이동
-
> refactor: 찜 목록, 로그인, 로그아웃 수정 [이태빈]

- src/app/(main)/order-history/page.tsx
- src/hooks/useOrderHistory.ts
- 구매내역확인 페이지에서 상품 목록 초기 데이터 로딩 시 최신순으로 정렬되어 있지 않고 임의로 표시되는 문제
- 상품 목록 초기 데이터 로딩 시 최신순으로 정렬되어 보이도록 개선
- /order-history 경로에서 초기 로딩 시 상품 목록이 최신순으로 정렬되어야 합니다
> feat: 상품 목록 초기 데이터 로딩 시 최신순으로 정렬 [김홍섭]

- src/app/error.tsx
- src/middleware.ts
-
- 글로벌에러페이지 `app/error.tsx` 추가
- `장바구니-주문`을 위한 쿼리파라미터 세팅
- 미들웨어 권한 차단하는 케이스(주석참고)
-
-
> feat: 미들웨어 역할별 접근제어 설정 추가, 글로벌 에러 페이지 추가

- src/middleware.ts
> fix: 미들웨어 긴급 케이스1

- src/middleware.ts
> fix: config 매처 주석

- src/middleware.ts
> fix: 미들웨어 경로 구체화

- src/middleware.ts
> fix: 컨픽 아예 빼기

- src/middleware.ts
> fix: 미들웨어 오류 다시

- src/middleware.ts
> fix: 로그인,회원가입 빼기

- src/app/(main)/products/[productId]/page.tsx
- 안쓰던 프롭스 제거하여 에러해결 했습니다
- 
-
-
> fix: 안쓰는 프롭스 제거 - 빌드에러 해결 [이지수B]

- src/middleware.ts
> fix: 미들웨어 활성화

- src/app/(auth)/login/page.tsx
- src/app/(main)/cart/_components/CartItem.tsx
- src/app/(main)/cart/order/_components/OrderItem.tsx
- src/app/(main)/my/favorites/page.tsx
- src/app/(toss-payments)/checkout/page.tsx
- src/app/(toss-payments)/success/_components/SuccessPageContent.tsx
- 로딩 스피너 처리 및 자잘한 수정 완료했습니다.
-
-
> feat: 로딩 스피너 처리 및 자잘한 수정 [이태빈]

- src/app/(main)/order-manage/[orderId]/page.tsx
- src/app/(main)/products/_components/ProductsPageContent.tsx
- src/components/common/SideMenu.tsx
- src/components/common/SubCategoryItem.tsx
- src/components/layout/AuthenticatedHeader.tsx
- src/types/auth.types.ts
- 미세한 UI 개선작업
- 불필요한 주석제거
- 빌드 오류 해결
멘토링 진행하며 나온 개선점 해결 하였습니다!
-
-
> refactor: 디자인 UI 개선 [이지수B]

- src/app/not-found.tsx
- 전역 not-found 컴포넌트를 추가합니다
- 전역 에러 컴포넌트들의 주석을 제거하여 가독성을 높입니다
- 전역 not-found 컴포넌트를 추가했습니다
- 전역 에러 컴포넌트들의 주석을 제거했습니다
- 직접 확인할 수 있을 정도로 적은 양의 변경사항이 있습니다. 코드 리뷰 후 승인 부탁드립니다
> feat: 전역 not-found 컴포넌트 추가 및 전역 에러 컴포넌트의 주석 제거 [김홍섭]

- src/components/chatbot/ChatWindow.tsx
- src/components/chatbot/FloatingButton.tsx
- src/hooks/useChat.ts
- 스낵 디자인과 잘 어울리도록 흰색&검은색 스타일로 플로팅버튼 및 채팅창 디자인을 개선했습니다.
- 플로팅버튼 및 채팅창 디자인을 개선했습니다.
- 팀의 의견에 따라 챗봇 플로팅버튼을 작게 변경했습니다
- 팀 컨벤션에 맞게 코드 스타일을 수정했습니다
- 코드 직접 열람 및 확인 가능
- 배포 및 개발 페이지에서 챗봇 사용 가능
> style: 챗봇 플로팅버튼, 채팅창 스타일 개선 [김홍섭]

- src/app/(main)/cart/page.tsx
- src/app/(toss-payments)/checkout/page.tsx
- src/app/(toss-payments)/success/_components/SuccessPageContent.tsx
- src/types/order.types.ts
- 스키마 변경에 따른 payment 페이지 변경했습니다.
-
-
> refactor: 스키마 변경에 따른 payment 페이지 변경 [이태빈]

- src/components/chatbot/ChatWindow.tsx
- src/components/chatbot/FloatingButton.tsx
- 챗봇&플로팅버튼에서 스타일 문법이 미적용되는 오류가 있어 수정하는 것이 목표
- 챗봇&플로팅버튼에서 스타일 문법이 미적용되는 오류가 있어 수정했습니다
- 개발 및 배포모드에서 스타일이 제대로 적용되었는지 확인 가능합니다
> fix: 챗봇&플로팅버튼 스타일 문법 오류 수정

- src/app/(main)/order-manage/_components/Order.tsx
- src/app/(toss-payments)/fail/_components/FailPageContent.tsx
- src/app/(toss-payments)/success/_components/SuccessPageContent.tsx
- src/components/common/OrderManageModal.tsx
- src/lib/api/orderManage.api.ts
- src/types/order.types.ts
- 결제 모듈 부족한 점 추가했습니다.
<장바구니 구현>
1. 주문 생성 시 유저 역할에 따라, status 분기처리 - O
2. 결제완료 하고 order 업데이트 할 때 order의 status 따라서, 즉시구매일 때만 adminMessage에 즉시 구매 추가 - O
3. order 불러오는 것 즉시 구매도 한번에 가져오도록 처리 - O
4. 유저가 요청한 것이 결제 실패 되었을 때에는 catch에서 롤백시키지 않고, 그냥 단순히 에러만 핸들링 해주도록 분기 처리 - O
5. 결제 취소했을 때 cancel 실행할 함수 생성 - O
6. 유저 구매요청을 승인할 때 adminMessage가 입력이 안되고 있는 현상 고치기 - O
7. 결제가 실패하면 유저의 요청 목록도 다시 되돌아 가도록 에러 핸들러 추가 - O
8. 결제 완료 했을 때 닫기 버튼 누르면 관리자는 -> 구매 완료 페이지, 유저 구매요청 승인은  -> 구매 요청 관리로 이동 시키기 - O
-
- Reviewer 분들은 좋은 코드를 발견한 경우, 칭찬과 격려를 아끼지 말아 …
> feat: 결제 모듈 부족한 점 추가 [이태빈]

- src/app/(main)/order-history/[orderId]/page.tsx
- src/app/(main)/order-manage/[orderId]/_components/OrderDetailSkeleton.tsx
- src/app/(main)/order-manage/[orderId]/page.tsx
- src/lib/utils/formatDate.util.ts
-
- formatDate 함수에 있던 '공백' 제거하였습니다.
- 구매요청관리 상세페이지 UI 자잘한거 수정했습니다 (컨벤션에 맞게 변수 사용 등).
-
> refactor: 구매요청관리 상세 페이지 미세 UI 개선, 스켈레톤 적용 [이지수B]

- src/app/(main)/products/_components/FlashToastConsumer.tsx
- src/stores/flashToast.ts
- 상품상세 페이지 수정
- 내 구매요청내역 페이지 수정 
- 상품 삭제 시, 상품리스트페이지로 이동 후 토스트 랜더링
- 상품삭제 드롭다운 위치 변경 
- 상품상세 페이지 이미지 출력 위치 변경
- 내 구매 요청내역 instant_approved 받을 수 있게 수정 
-
> hotfix:상품상세 페이지 수정, 내 구매요청내역 페이지 instant_approved받을 수 있게 수정 [조성빈]

- src/app/(main)/my/order-list/page.tsx
- src/app/(main)/products/page.tsx
- src/components/common/MenuDropdown.tsx
- src/components/common/MyRequestList.tsx
- src/components/common/ProductDetail.tsx
- src/components/common/ProductDetail/ProductActions.tsx
- src/components/common/ProductDetail/ProductImage.tsx
- src/lib/utils/convertStatus.util.ts
> hotfix: 변경사항 적용안된거 다시pr [조성빈]

- src/lib/utils/cookie.util.ts
- 백엔드 API에도 SameSite 설정이 Lax로 되어있고, Strict로 인해 발생할 혹시모를 쿠키 문제를 방지하기 위해 Lax로 설정
- 백엔드 API에도 SameSite 설정이 Lax로 되어있고, Strict로 인해 발생할 혹시모를 쿠키 문제를 방지하기 위해 Lax로 설정
- 배포환경에서 로그아웃이 잘 되면 테스트 완료입니다.
- P3 : 이런 방법도 있을 것 같아요~ 등의 사소한 의견입니다 …
> feat: SameSite Strict 대신 Lax 사용하도록 수정 [김홍섭]

- src/app/(main)/manage/users/_components/User.tsx
- src/components/common/MemberList.tsx
- src/components/ui/Badge.tsx
- src/lib/api/fetchClient.api.ts
> fix: 회원 관리에 나온 오류 수정 [김우주]

- src/app/(main)/order-history/page.tsx
- src/components/chatbot/ChatWindow.tsx
- src/components/chatbot/FloatingButton.tsx
- src/hooks/useOrderHistory.ts
[모의발표 핫픽스 2차 수정했습니다]
• [x] 구매 내역 확인 페이지 진입 시 최신 순으로 정렬 안되는 현상 → 확인해보니 “구매 승인일” 기준 최신순으로 정렬 잘 되고있는 것 같습니다. 수정 사항 없음
• [x] 로그인 풀려요 리프레쉬토큰 요청 안들어가는 현상
• [x] 로그아웃 요청 보내도 refresh & accesstoken 삭제 안되는 현상 - 백엔드 auth.controller 혹은 지수 프론트에서 logout 함수 체크
• [x] 이미 로그인 되어있다면, 같은 플랫폼(브라우저)에서 snack을 들어오더라도 중복 로그인 안되도록 해야한다.(애초에 로그인 창으로 못 들어가게 해야 한다고 합니다.)
• [x] NoContent 사용 시 중앙 정렬 안되어있음, 하단 패딩 조금 필요 → [오전 10시 17분 커밋]
• [x] order-history의 색상이 조금 다름, 확인 요망 → [오전 9시 50분 커밋]
• [x] 구매내역 확인페이지- 금액 NaN 으로 나오는점 → [오전 9시 42분 커밋]
• [x] 구매내역 확인페이지 - 즉시구매였으면 뱃지 나오게 → [오전 9시 35분 커밋] → [오전 10:38분 개선 확인 커밋]
• [x] 구매내역확인 페이지 페이지네이션 Next > 부분 disabled 됫을때 not allowed 말고 cursor-default로 …
> 핫픽스 2차: 문제 해결 PR (이슈 목록 중 미들웨어 이슈 제외) [김홍섭]

- src/app/(main)/my/order-list/page.tsx
- src/types/myOrderList.types.ts
- hotfix:스키마 변경에 따른 주문금액 NaN으로 출력되는 현상 수정
- hotfix:스키마 변경에 따른 주문금액 NaN으로 출력되는 현상 수정
-
> hotfix:스키마 변경에 따른 주문금액 NaN으로 출력되는 현상 수정 [조성빈]

- src/app/(auth)/signup/[inviteId]/page.tsx
- 비밀번호, 비밀번호 확인 label에 애니메이션 추가
- 비밀번호, 비밀번호 확인 일치하게 입력했다가 다시 비밀번호에서 수정시 비밀번호 확인에 유효성 검사가 트리거 되지 않던 문제 해결
- 이 부분에 갭 주었음 (구조상 ml-1 적용)
- <img width="212" height="34" alt="Screenshot 2025-08-12 at 11 05 03 PM" src="https://github.com/user-attachments/assets/497441b2-e7a9-4c5f-9ce4-1af1b43322dd" />
- 여기 에러메세지 날때 보더색깔이 빨갛게 변하지 않던점 수정
- <img width="485" height="78" alt="Screenshot 2025-08-12 at 11 05 38 PM" src="https://github.com/user-attachments/assets/266f7850-5308-4ad5-b675-9004aa4532ea" />
-
-
- Reviewer 분들은 좋은 코드를 발견한 경우, …
> fix: 회원가입 페이지 핫픽스 개선 [이지수B]

- src/middleware.ts
- /manage/users, /manage/budgets
→ SUPER_ADMIN만 접근 가능.
→ USER, ADMIN이 접근 시 /unauthorized로 리디렉션.
- /order-manage, /order-history
→ USER는 접근 불가(ADMIN, SUPER_ADMIN만 접근 가능).
→ USER가 접근 시 /unauthorized로 리디렉션.
- /cart/order
→ ADMIN, SUPER_ADMIN은 접근 불가(USER만 접근 가능).
→ ADMIN, SUPER_ADMIN이 접근 시 /unauthorized?from=order로 리디렉션.
- accessToken과 refreshToken 모두 없으면
→ "/"(랜딩), "/login", "/signup"만 접근 가능.
→ 그 외 경로는 /login으로 리디렉션.
- refreshToken만 있고 accessToken이 없는 경우
→ 보호된 페이지 접근을 차단하지 않음(즉, 페이지로 흘려보냄).
→ 클라이언트에서 자동 accessToken 재발급(401 발생 시) 로직이 동작할 수 있도록 허용.
- 위와 같습니다
- 배포, 로컬 환경에서 미들웨어 동작 확인
- …
> feat: /manage/users, /manage/budgets 경로에 대해 USER, ADMIN 접근 차단 (SUPER_ADMIN만 허용) [김홍섭]

- src/app/(main)/order-history/page.tsx
- 3000원 추가로 표시하는 오류 개선
- mx-auto, max-w-xxxpx 값 삭제로 간격 개선
- 3000원 추가로 표시하는 오류 개선
- mx-auto, max-w-xxxpx 값 삭제로 간격 개선
- 배포 및 개발 환경에서 확인 가능합니다
> fix: 3000원 추가로 표시하는 오류 개선, mx-auto max-w-xxxpx 삭제 [김홍섭]

- src/components/svg/TimeIconSvg.tsx
- src/components/ui/Badge.tsx
> feat: 시계 svg로 추가했습니다[김우주]

- src/components/common/NoContent.tsx
- NoContent 컴포넌트 props 수정했습니다. className으로 원하시는 스타일링으로 변경하실 수 있습니다.
-
-
> refactor: NoContent 컴포넌트 props 수정 [이태빈]

- src/app/(main)/order-history/page.tsx
- Prev와 Next 버튼 색상 일치, NoContent Props 사용으로 상품 없을 시 UI 개선했습니다
- Prev와 Next 버튼 색상은 text-primary-800으로 적용, NoContent에서 Margin Top Props 속성 사용과 Padding Bottom 값 변경으로 상품 없을 시 UI 개선했습니다
- 개발 및 배포 모드에서 확인 가능합니다
- P3 : 이런 방법도 있을 것 같아요~ …
> fix: Prev와 Next 버튼 색상 일치, NoContent Props 사용으로 UI 개선

- src/app/(toss-payments)/checkout/page.tsx
- src/hooks/usePreventLeave.ts
- feat: 결제에서 사용자가 취소 시 되돌리는 함수 추가
-
-
> feat: 결제에서 사용자가 취소 시 되돌리는 함수 추가 [이태빈]
